"""add unique constraint to teacher_id in subject

Revision ID: 2621dcefe342
Revises: 5df859e79299
Create Date: 2025-05-12 22:23:11.326055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2621dcefe342'
down_revision: Union[str, None] = '5df859e79299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subjects_teacher_id', 'subjects', ['teacher_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subjects_teacher_id', 'subjects', type_='unique')
    # ### end Alembic commands ###
