"""remove deprecated columns from requests table

Revision ID: 53c3a6a591aa
Revises: db2be668f43a
Create Date: 2025-08-10 18:45:33.887041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c3a6a591aa'
down_revision: Union[str, None] = 'db2be668f43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_subject_id_fkey', 'requests', type_='foreignkey')
    op.drop_constraint('requests_teacher_id_fkey', 'requests', type_='foreignkey')
    op.drop_constraint('requests_student_id_fkey', 'requests', type_='foreignkey')
    op.drop_column('requests', 'student_id')
    op.drop_column('requests', 'subject_id')
    op.drop_column('requests', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('subject_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('requests_student_id_fkey', 'requests', 'users', ['student_id'], ['id'])
    op.create_foreign_key('requests_teacher_id_fkey', 'requests', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key('requests_subject_id_fkey', 'requests', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
