"""add remark field to certificate

Revision ID: a4c0e7f6eded
Revises: 31acd1df1ad1
Create Date: 2025-05-19 14:08:29.615019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c0e7f6eded'
down_revision: Union[str, None] = '31acd1df1ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'remark')
    # ### end Alembic commands ###
