"""add teacher_subject_allotment_id to student_subject_enrollments

Revision ID: cc2292cdad1a
Revises: b8685ba94eaf
Create Date: 2025-08-09 17:47:16.726304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2292cdad1a'
down_revision: Union[str, None] = 'b8685ba94eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the column as nullable first
    op.add_column('student_subject_enrollments', sa.Column('teacher_subject_allotment_id', sa.String(), nullable=True))
    
    # Step 2: Populate the column with matching teacher_subject_allotment_id
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE student_subject_enrollments 
        SET teacher_subject_allotment_id = tsa.id
        FROM teacher_subject_allotments tsa
        WHERE student_subject_enrollments.subject_id = tsa.subject_id 
        AND student_subject_enrollments.teacher_id = tsa.teacher_id
    """))
    
    # Step 3: Make the column non-null
    op.alter_column('student_subject_enrollments', 'teacher_subject_allotment_id', nullable=False)
    
    # Step 4: Add the foreign key constraint
    op.create_foreign_key(None, 'student_subject_enrollments', 'teacher_subject_allotments', ['teacher_subject_allotment_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_subject_enrollments', type_='foreignkey')
    op.drop_column('student_subject_enrollments', 'teacher_subject_allotment_id')
    # ### end Alembic commands ###
