"""remove deprecated columns from student and student enrollments

Revision ID: db2be668f43a
Revises: cc2292cdad1a
Create Date: 2025-08-10 17:16:20.489805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2be668f43a'
down_revision: Union[str, None] = 'cc2292cdad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_subjects_student_id_subject_id_year_is_sem_odd_key', 'student_subject_enrollments', type_='unique')
    op.create_unique_constraint(None, 'student_subject_enrollments', ['student_id', 'teacher_subject_allotment_id'])
    op.drop_constraint('student_subjects_subject_id_fkey', 'student_subject_enrollments', type_='foreignkey')
    op.drop_constraint('student_subjects_teacher_id_fkey', 'student_subject_enrollments', type_='foreignkey')
    op.drop_column('student_subject_enrollments', 'subject_id')
    op.drop_column('student_subject_enrollments', 'teacher_id')
    op.drop_column('student_subject_enrollments', 'is_sem_odd')
    op.drop_column('student_subject_enrollments', 'year')
    op.drop_constraint('subjects_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('subjects_teacher_id_fkey', 'subjects', 'users', ['teacher_id'], ['id'])
    op.add_column('student_subject_enrollments', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_subject_enrollments', sa.Column('is_sem_odd', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('student_subject_enrollments', sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student_subject_enrollments', sa.Column('subject_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('student_subjects_teacher_id_fkey', 'student_subject_enrollments', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key('student_subjects_subject_id_fkey', 'student_subject_enrollments', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'student_subject_enrollments', type_='unique')
    op.create_unique_constraint('student_subjects_student_id_subject_id_year_is_sem_odd_key', 'student_subject_enrollments', ['student_id', 'subject_id', 'year', 'is_sem_odd'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
