"""edit unique constraint for teacher subject allotments

Revision ID: fbd103d62084
Revises: 53c3a6a591aa
Create Date: 2025-08-13 10:18:23.378440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd103d62084'
down_revision: Union[str, None] = '53c3a6a591aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_subject_allotments_teacher_id_subject_id_year_is_se_key', 'teacher_subject_allotments', type_='unique')
    op.create_unique_constraint(None, 'teacher_subject_allotments', ['subject_id', 'year', 'is_sem_odd'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_subject_allotments', type_='unique')
    op.create_unique_constraint('teacher_subject_allotments_teacher_id_subject_id_year_is_se_key', 'teacher_subject_allotments', ['teacher_id', 'subject_id', 'year', 'is_sem_odd'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
