"""add subject code

Revision ID: 7dc6b0df0ee0
Revises: 2621dcefe342
Create Date: 2025-05-13 14:50:18.957084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc6b0df0ee0'
down_revision: Union[str, None] = '2621dcefe342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('subject_code', sa.String(), nullable=False))
    op.create_unique_constraint('uq_subject_code', 'subjects', ['subject_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subject_code', 'subjects', type_='unique')
    op.drop_column('subjects', 'subject_code')
    # ### end Alembic commands ###
