"""add no_certificate file to requeststatus

Revision ID: 08efb1a7ad99
Revises: 28fad01a8f5b
Create Date: 2025-05-27 21:36:03.095411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08efb1a7ad99'
down_revision: Union[str, None] = '28fad01a8f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE requeststatus ADD VALUE 'no_certificate' AFTER 'completed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
