"""add under_review status to RequestStatus enum

Revision ID: 5153f1a3b3a3
Revises: 3a044bf3b93c
Create Date: 2025-06-22 06:35:50.886251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5153f1a3b3a3'
down_revision: Union[str, None] = '3a044bf3b93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE requeststatus ADD VALUE 'under_review' AFTER 'no_certificate'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
